import { HttpErrorResponse } from '@angular/common/http'; import { computed,inject,Injectable,signal } from '@angular/core'; import { finalize,forkJoin,Observable } from 'rxjs'; import { CatalogOption } from '../../../core/catalogs/catalog.models'; import { CatalogsApiService } from '../../../core/catalogs/catalogs-api.service';
import { BatchResult,EligibleReading,GenerateBatchInput,GenerateInvoiceInput,Invoice } from '../domain/invoice.models'; import { InvoicesApiService } from '../infrastructure/invoices-api.service';
@Injectable() export class InvoicesFacade {private readonly api=inject(InvoicesApiService);private readonly catalogs=inject(CatalogsApiService);readonly invoices=signal<Invoice[]>([]);readonly periods=signal<CatalogOption[]>([]);readonly closedPeriods=signal<CatalogOption[]>([]);readonly eligible=signal<EligibleReading[]>([]);readonly selected=signal<Invoice|null>(null);readonly loading=signal(false);readonly saving=signal(false);readonly error=signal<string|null>(null);readonly notice=signal<string|null>(null);readonly batchResult=signal<BatchResult|null>(null);readonly page=signal(1);readonly limit=signal(10);readonly totalPages=signal(1);readonly filters=signal<Record<string,string>>({});readonly hasPrevious=computed(()=>this.page()>1);readonly hasNext=computed(()=>this.page()<this.totalPages());
  load(){this.loading.set(true);this.api.list(this.page(),this.limit(),this.filters()).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.invoices.set(r.data);this.totalPages.set(r.meta.totalPages)},error:e=>this.fail(e)})}
  loadCatalogs(){forkJoin({all:this.catalogs.get('billing-periods'),closed:this.catalogs.get('billing-periods',{status:'CLOSED'})}).subscribe({next:r=>{this.periods.set(r.all);this.closedPeriods.set(r.closed)},error:e=>this.fail(e)})}
  loadEligible(id:number|null){this.eligible.set([]);if(!id)return;this.api.eligible(id).subscribe({next:r=>this.eligible.set(r.data),error:e=>this.fail(e)})}
  detail(id:number){this.api.one(id).subscribe({next:v=>this.selected.set(v),error:e=>this.fail(e)})}
  applyFilters(search:string,filters:Record<string,string>){this.filters.set({...filters,...(search&&{search})});this.page.set(1);this.load()}
  previous(){if(this.hasPrevious()){this.page.update(v=>v-1);this.load()}} next(){if(this.hasNext()){this.page.update(v=>v+1);this.load()}}
  generate(input:GenerateInvoiceInput){this.mutate(this.api.generate(input),'Factura generada correctamente.')}
  generateBatch(input:GenerateBatchInput){this.saving.set(true);this.clear();this.api.batch(input).pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.batchResult.set(r);this.notice.set(`Proceso terminado: ${r.generatedCount} facturas generadas y ${r.errorCount} errores.`);this.load()},error:e=>this.fail(e)})}
  issue(v:Invoice){this.mutate(this.api.issue(v.id),'Factura emitida correctamente.')} void(v:Invoice,reason:string){this.mutate(this.api.void(v.id,reason),'Factura anulada correctamente.')}
  clear(){this.error.set(null);this.notice.set(null);this.batchResult.set(null)}
  private mutate(request:Observable<Invoice>,message:string){this.saving.set(true);this.clear();request.pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>{this.notice.set(message);this.load()},error:e=>this.fail(e)})}
  private fail(error:HttpErrorResponse){this.error.set(typeof error.error?.message==='string'?error.error.message:'No fue posible completar la operación.')}
}
