import { CurrencyPipe,DatePipe,DecimalPipe } from '@angular/common'; import { Component,computed,inject,OnInit,signal } from '@angular/core'; import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms'; import { MatButtonModule } from '@angular/material/button'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatSelectModule } from '@angular/material/select'; import { MatTooltipModule } from '@angular/material/tooltip';
import { ActionIconComponent } from '../../../shared/components/action-icon/action-icon.component'; import { DateFieldComponent } from '../../../shared/components/date-field/date-field.component'; import { ListFilterField,ListFiltersComponent } from '../../../shared/components/list-filters/list-filters.component'; import { AuthSessionService } from '../../auth/application/auth-session.service'; import { InvoicesFacade } from '../application/invoices.facade'; import { INVOICE_STATUS_LABELS,Invoice,InvoiceStatus } from '../domain/invoice.models';
import { ModalComponent } from '../../../shared/components/modal/modal.component'; import { NotificationComponent } from '../../../shared/components/notification/notification.component';
import { ConfirmationDialogService } from '../../../shared/components/confirmation-dialog/confirmation-dialog.service';
import { ExcelExportService } from '../../../shared/services/excel-export.service';
import { InvoiceBatchPreviewComponent } from './invoice-batch-preview.component';
@Component({
  selector: 'app-invoices-page',
  standalone: true,
  imports: [ActionIconComponent, ModalComponent, NotificationComponent, CurrencyPipe, DateFieldComponent, DatePipe, DecimalPipe, InvoiceBatchPreviewComponent, ListFiltersComponent, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatTooltipModule, ReactiveFormsModule],
  providers: [InvoicesFacade],
  templateUrl: './invoices.page.html',
  styleUrl: './invoices.page.scss',
})
export class InvoicesPage implements OnInit {readonly facade=inject(InvoicesFacade);private readonly session=inject(AuthSessionService);private readonly confirmation=inject(ConfirmationDialogService);private readonly excel=inject(ExcelExportService);readonly formOpen=signal(false);readonly batchOpen=signal(false);readonly batchPeriodId=signal<number|null>(null);readonly canWrite=computed(()=>{const r=this.session.user()?.roles??[];return r.includes('ADMIN')||r.includes('OPERADOR')});readonly canVoid=computed(()=>this.session.user()?.roles?.includes('ADMIN')??false);readonly filterFields=computed<ListFilterField[]>(()=>[{key:'status',label:'Estado',type:'select',options:Object.entries(INVOICE_STATUS_LABELS).map(([value,label])=>({value,label}))},{key:'billingPeriodId',label:'Periodo',type:'select',options:this.facade.periods()}]);
  readonly form=new FormGroup({mode:new FormControl<'batch'|'single'>('batch',{nonNullable:true}),billingPeriodId:new FormControl<number|null>(null,{validators:Validators.required}),meterReadingId:new FormControl<number|null>(null),issueDate:new FormControl('',{nonNullable:true}),dueDate:new FormControl('',{nonNullable:true})});
  ngOnInit(){this.facade.loadCatalogs();this.facade.load();this.form.controls.billingPeriodId.valueChanges.subscribe(id=>this.facade.loadEligible(id))}
  exportExcel(){this.excel.download('invoices','facturas',this.facade.filters()).subscribe()}
  openBatch(periodId?:number){const id=periodId??Number(this.facade.filters()['billingPeriodId']);if(!id){this.facade.error.set('Selecciona un periodo en los filtros para gestionar su lote de facturación.');return}this.batchPeriodId.set(id);this.batchOpen.set(true);this.facade.batchSummary.set(null);this.facade.loadBatchSummary(id)}
  closeBatch(){this.batchOpen.set(false);this.batchPeriodId.set(null)}
  async issueBatch(){const id=this.batchPeriodId();const summary=this.facade.batchSummary();if(!id||!summary)return;const confirmed=await this.confirmation.confirm({title:'Emitir lote de facturación',message:`¿Deseas emitir ${summary.statuses.DRAFT??0} facturas del periodo ${String(summary.billingPeriod.month).padStart(2,'0')}/${summary.billingPeriod.year}? Después quedarán listas para entregar.`,confirmLabel:'Sí, emitir lote'});if(confirmed)this.facade.issueBatch(id)}
  printBatch(part:number){const id=this.batchPeriodId();if(id)this.facade.printBatch(id,part)}
  downloadBatchZip(){const id=this.batchPeriodId();if(id)this.facade.downloadBatchZip(id)}
  openGenerate(){this.form.reset({mode:'batch',billingPeriodId:null,meterReadingId:null,issueDate:'',dueDate:''});this.facade.clear();this.formOpen.set(true)} closeGenerate(){this.formOpen.set(false)} closeDetail(){this.facade.selected.set(null)}
  submit(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();if(!v.billingPeriodId)return;const dates={...(v.issueDate&&{issueDate:v.issueDate}),...(v.dueDate&&{dueDate:v.dueDate})};if(v.mode==='single'){if(!v.meterReadingId){this.facade.error.set('Selecciona una lectura pendiente.');return}this.facade.generate({meterReadingId:v.meterReadingId,...dates})}else{const periodId=v.billingPeriodId;this.facade.generateBatch({billingPeriodId:periodId,...dates},()=>this.openBatch(periodId))}this.closeGenerate()}
  async issue(v:Invoice){const confirmed=await this.confirmation.confirm({title:'Emitir factura',message:`¿Deseas emitir la factura ${this.number(v)}?`,confirmLabel:'Sí, emitir'});if(confirmed)this.facade.issue(v)} async void(v:Invoice){const reason=await this.confirmation.prompt({title:'Anular factura',message:`Indica el motivo para anular la factura ${this.number(v)}.`,inputLabel:'Motivo de anulación',inputPlaceholder:'Escribe el motivo',confirmLabel:'Anular factura',danger:true});if(reason)this.facade.void(v,reason)} number(v:Invoice){return `FAC-${String(v.sequence).padStart(6,'0')}`} status(v:InvoiceStatus){return INVOICE_STATUS_LABELS[v]}
  readingLabel(id:number){const r=this.facade.eligible().find(v=>v.id===id);return r?`${r.meter.serialNumber} · ${r.meter.property.customer.firstName} ${r.meter.property.customer.lastName}`:String(id)}
}
