import { CurrencyPipe,DatePipe,DecimalPipe } from '@angular/common'; import { Component,computed,inject,OnInit,signal } from '@angular/core'; import { FormControl,FormGroup,ReactiveFormsModule,Validators } from '@angular/forms'; import { MatButtonModule } from '@angular/material/button'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatSelectModule } from '@angular/material/select'; import { MatTooltipModule } from '@angular/material/tooltip';
import { ActionIconComponent } from '../../../shared/components/action-icon/action-icon.component'; import { DateFieldComponent } from '../../../shared/components/date-field/date-field.component'; import { ListFilterField,ListFiltersComponent } from '../../../shared/components/list-filters/list-filters.component'; import { AuthSessionService } from '../../auth/application/auth-session.service'; import { InvoicesFacade } from '../application/invoices.facade'; import { INVOICE_STATUS_LABELS,Invoice,InvoiceStatus } from '../domain/invoice.models';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
@Component({selector:'app-invoices-page',imports:[ActionIconComponent,ModalComponent,CurrencyPipe,DateFieldComponent,DatePipe,DecimalPipe,ListFiltersComponent,MatButtonModule,MatFormFieldModule,MatInputModule,MatSelectModule,MatTooltipModule,ReactiveFormsModule],providers:[InvoicesFacade],templateUrl:'./invoices.page.html',styleUrl:'./invoices.page.scss'})
export class InvoicesPage implements OnInit {readonly facade=inject(InvoicesFacade);private readonly session=inject(AuthSessionService);readonly formOpen=signal(false);readonly canWrite=computed(()=>{const r=this.session.user()?.roles??[];return r.includes('ADMIN')||r.includes('OPERADOR')});readonly canVoid=computed(()=>this.session.user()?.roles?.includes('ADMIN')??false);readonly filterFields=computed<ListFilterField[]>(()=>[{key:'status',label:'Estado',type:'select',options:Object.entries(INVOICE_STATUS_LABELS).map(([value,label])=>({value,label}))},{key:'billingPeriodId',label:'Periodo',type:'select',options:this.facade.periods()}]);
  readonly form=new FormGroup({mode:new FormControl<'batch'|'single'>('batch',{nonNullable:true}),billingPeriodId:new FormControl('',{nonNullable:true,validators:Validators.required}),meterReadingId:new FormControl('',{nonNullable:true}),issueDate:new FormControl('',{nonNullable:true}),dueDate:new FormControl('',{nonNullable:true})});
  ngOnInit(){this.facade.loadCatalogs();this.facade.load();this.form.controls.billingPeriodId.valueChanges.subscribe(id=>this.facade.loadEligible(id))}
  openGenerate(){this.form.reset({mode:'batch',billingPeriodId:'',meterReadingId:'',issueDate:'',dueDate:''});this.facade.clear();this.formOpen.set(true)} closeGenerate(){this.formOpen.set(false)} closeDetail(){this.facade.selected.set(null)}
  submit(){if(this.form.invalid){this.form.markAllAsTouched();return}const v=this.form.getRawValue();const dates={...(v.issueDate&&{issueDate:v.issueDate}),...(v.dueDate&&{dueDate:v.dueDate})};if(v.mode==='single'){if(!v.meterReadingId){this.facade.error.set('Selecciona una lectura pendiente.');return}this.facade.generate({meterReadingId:v.meterReadingId,...dates})}else this.facade.generateBatch({billingPeriodId:v.billingPeriodId,...dates});this.closeGenerate()}
  issue(v:Invoice){if(confirm(`¿Emitir la factura ${this.number(v)}?`))this.facade.issue(v)} void(v:Invoice){const reason=prompt('Motivo de anulación:')?.trim();if(reason)this.facade.void(v,reason)} number(v:Invoice){return `FAC-${String(v.sequence).padStart(6,'0')}`} status(v:InvoiceStatus){return INVOICE_STATUS_LABELS[v]}
  readingLabel(id:string){const r=this.facade.eligible().find(v=>v.id===id);return r?`${r.meter.serialNumber} · ${r.meter.property.customer.firstName} ${r.meter.property.customer.lastName}`:id}
}
